$html = [System.IO.File]::ReadAllText("index.html")
$html = $html.Replace("IMAGENES/UBICACIÓN/", "SECCIONES/UBICACIÓN/IMAGENES/")
$html = $html.Replace("IMAGENES/lasierra_residencial_", "SECCIONES/PROTOTIPOS/GALERIA DE PLANOS/lasierra_residencial_")
$html = $html.Replace("IMAGENES/La sierra Residencial A.png", "LOGOS/La sierra Residencial A.png")
$html = $html.Replace("IMAGENES/La sierra Residencial B.png", "LOGOS/La sierra Residencial B.png")
$html = $html.Replace("IMAGENES/La Sierra 2.jpg", "SECCIONES/PROYECTO/IMAGENES/La Sierra 2.jpg")
$html = $html.Replace("IMAGENES/La Sierra 3.jpg", "SECCIONES/PROYECTO/IMAGENES/La Sierra 3.jpg")
$html = $html.Replace("IMAGENES/La Sierra 6.jpg", "SECCIONES/PROYECTO/IMAGENES/La Sierra 6.jpg")
$html = $html.Replace("IMAGENES/La Sierra 7.jpg", "SECCIONES/PROYECTO/IMAGENES/La Sierra 7.jpg")
$html = $html.Replace("IMAGENES/WhatsApp Image 2025-11-18 at 9.17.31 AM (7).jpeg", "SECCIONES/PROYECTO/IMAGENES/WhatsApp Image 2025-11-18 at 9.17.31 AM (7).jpeg")
$html = $html.Replace("IMAGENES/WhatsApp Image 2025-11-18 at 9.17.32 AM (1).jpeg", "SECCIONES/PROYECTO/IMAGENES/WhatsApp Image 2025-11-18 at 9.17.32 AM (1).jpeg")
$html = $html.Replace("IMAGENES/WhatsApp Image 2025-11-18 at 9.17.32 AM.jpeg", "SECCIONES/PROYECTO/IMAGENES/WhatsApp Image 2025-11-18 at 9.17.32 AM.jpeg")
$html = $html.Replace("VIDEOS/20251106_222310000_iOS.MP4", "SECCIONES/PROYECTO/VIDEOS/20251106_222310000_iOS.MP4")
[System.IO.File]::WriteAllText("index.html", $html)

$css = [System.IO.File]::ReadAllText("style.css")
$css = $css.Replace("IMAGENES/La Sierra (3).png", "SECCIONES/HERO/IMAGENES/La Sierra (3).png")
$css = $css.Replace("IMAGENES/La Sierra 5.jpg", "SECCIONES/CONTACTO/IMAGENES/La Sierra 5.jpg")
[System.IO.File]::WriteAllText("style.css", $css)
